<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>038bbd32-96dc-40f7-8a1d-2458124400d9</uuid>
	<name>External Outlet Fan 1</name>
	<type>43</type>
	<res_file_key>8c7e14aa-1db8-448a-ba8d-d13942ef54e9</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>false</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<transparency>0</transparency>
	<use_all_faces>false</use_all_faces>
	<geom_ref/>
	<parameter>
		<item>
			<type>1</type>
			<dependency_type>0</dependency_type>
			<value>293.19999999999999</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>5</type>
			<dependency_type>0</dependency_type>
			<value>101325</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>118</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>119</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>120</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>121</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>122</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>123</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>124</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>125</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>126</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>127</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>130</type>
			<dependency_type>0</dependency_type>
			<value>0.75</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>131</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>201</type>
			<dependency_type>0</dependency_type>
			<value>2</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>202</type>
			<dependency_type>0</dependency_type>
			<value>0.00075197674418604657</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>203</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>204</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>999</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1001</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1002</type>
			<dependency_type>0</dependency_type>
			<value>200</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1012</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1013</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1018</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1019</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1037</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1039</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1106</type>
			<dependency_type>0</dependency_type>
			<value>101325</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1107</type>
			<dependency_type>0</dependency_type>
			<value>293.19999999999999</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1108</type>
			<dependency_type>0</dependency_type>
			<value>50</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1115</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1132</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1135</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1136</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1228</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1229</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1322</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1429</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1478</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
	</parameter>
	<fan_type>1</fan_type>
</feature>
