<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>2b472a9a-1586-4950-8520-2ffff855b1fb</uuid>
	<name>Real Wall 3</name>
	<type>40</type>
	<res_file_key>a3e491b4-2a0d-454c-9b70-2b265f6eff6d</res_file_key>
	<cs_name/>
	<cs_uuid>64027020-f2c1-4495-83cb-22a3d2c55a47</cs_uuid>
	<x_form>
		<global>false</global>
		<origin>
			<item>-1.446989492596751e-08</item>
			<item>0.0010952748541153462</item>
			<item>1.7929407521680761e-07</item>
		</origin>
		<translate>
			<item>0</item>
			<item>1</item>
			<item>-0</item>
			<item>1</item>
			<item>0</item>
			<item>-0</item>
			<item>0</item>
			<item>0</item>
			<item>-1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>false</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<transparency>0</transparency>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>64027020-f2c1-4495-83cb-22a3d2c55a47</uuid>
			<name/>
			<type>-1</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>0</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid/>
			<origin>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</origin>
			<normal>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</normal>
			<vector>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>0</min>
			<max>0</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<parameter>
		<item>
			<type>1</type>
			<dependency_type>0</dependency_type>
			<value>293.19999999999999</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>3</type>
			<dependency_type>0</dependency_type>
			<value>101325</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>4</type>
			<dependency_type>0</dependency_type>
			<value>101325</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>6</type>
			<dependency_type>0</dependency_type>
			<value>101325</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>7</type>
			<dependency_type>0</dependency_type>
			<value>101325</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>100</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>101</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>102</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>103</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>104</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>105</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>106</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>107</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>108</type>
			<dependency_type>0</dependency_type>
			<value>0.0001</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>109</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>110</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>111</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>112</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>113</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>114</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>115</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>116</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>117</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>128</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>201</type>
			<dependency_type>0</dependency_type>
			<value>2</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>202</type>
			<dependency_type>0</dependency_type>
			<value>0.00075197674418604657</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>203</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>204</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>401</type>
			<dependency_type>0</dependency_type>
			<value>293.19999999999999</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>403</type>
			<dependency_type>0</dependency_type>
			<value>293.19999999999999</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>404</type>
			<dependency_type>0</dependency_type>
			<value>293.19999999999999</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>600</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>601</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>602</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>700</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>999</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1000</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1001</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1002</type>
			<dependency_type>0</dependency_type>
			<value>200</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1003</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1005</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1021</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1022</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1023</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1031</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1036</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1037</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1038</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1039</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1078</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1093</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1106</type>
			<dependency_type>0</dependency_type>
			<value>101325</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1107</type>
			<dependency_type>0</dependency_type>
			<value>293.19999999999999</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1108</type>
			<dependency_type>0</dependency_type>
			<value>50</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1111</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1115</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1135</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1136</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1228</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1229</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1322</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1323</type>
			<dependency_type>0</dependency_type>
			<value>0.0001</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1324</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1326</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1327</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1328</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>true</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1330</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1429</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1474</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1478</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
	</parameter>
	<flow_cond_type>301</flow_cond_type>
</feature>
